version: '2'
services:
  web:
    build: .
    environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres/wiki
    links: 
    - postgres
    ports:
    - "3000:3000"
  postgres:
    build: ./db
    volumes:
    - postgres_db:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=wiki
    - PGPASSWORD=postgres
volumes:
  postgres_db: {}